#########################################################################
# Если мы когда-нибудь встретимся, и ты считаешь, что этот плагин стоит #
# того, можешь купить мне пива взамен.                                  #
#                                                 С любовью, @alcoloid  #
#########################################################################

compass-settings:
  # Тип отображения компаса. Доступные значения: actionbar, bossbar
  type: bossbar
  # Cтиль отображения компаса. Доступные значения: degrees, simple, rust
  display: rust
  bossbar:
    # Цвет полоски боссбара. Доступные цвета:
    # PINK, BLUE, RED, GREEN, YELLOW, PURPLE, WHITE
    color: WHITE
    # Должна ли полоска боссбара менять свой прогресс зависимо от
    # поворота головы игрока
    progress: false

display-settings:
  degrees:
    # Цвет отображения углов на компасе (display: degrees)
    angle-color: '#FFFFFF'
    # Цвет отображения центрального угла на компасе (display: degrees)
    angle-color-center: '#9966CC'
  rust:
    # Цвет всего компаса (display: rust)
    color: '#FFFFFF'

waypoint-settings:
  # Цвет отображения кардинальных направлений (N, NE, E, ...)
  cardinal-color: '#00FFFF'
  # Символ, используемый для обозначения точки дома на компасе
  home-marker: '▼'

# Отображать точки дома из Essentials на компасе?
essentials-home: true