name: HorizontalCompass
version: '${version}'
main: com.github.alcoloid0.horizontalcompass.HorizontalCompass
api-version: '1.16'
authors: [ alcoloid ]
softdepend:
  - ProtocolLib
commands:
  horizontalcompass:
    aliases: [ hcompass ]
