name: HorizontalCompassHomes
version: '${version}'
main: com.github.alcoloid0.horizontalcompass.homes.HorizontalCompassHomes
api-version: '1.16'
authors: [ alcoloid ]
depend:
  - Essentials
  - HorizontalCompass